### PR TITLE
Search and follow Bugs

### PR DESCRIPTION
**Pull request by LinX64**

### CODE REVIEW

**Comment by LinX64** [comment]
[Map screen: when pressing back from top toolbar, search screen does not retain previously searched place](https://trello.com/c/zJK0Xyv3/1686-map-screen-when-pressing-back-from-top-toolbar-search-screen-does-not-retain-previously-searched-place)

**Review by xameYeoh — CHANGES_REQUESTED** [review]
Still not working on my side - goes to the dashboard

**Comment by LinX64** [comment]
> Still not working on my side - goes to the dashboard

Can't test this because of my IP and restrictions. I'll fix it from Home.

**Comment by LinX64** [comment]
It should work as expected now, for both navigation and data saving when replacing another fragment.

**Review by xameYeoh — APPROVED** [review]
Cool!

**Pull request merged**
