### PR TITLE
Mobile active > add a note: attach photo - UI

### PR DESCRIPTION
**Pull request by LinX64**

### CODE REVIEW

**Comment by LinX64** [comment]
[Mobile active > add a note: attach photo](https://trello.com/c/TL4MVMzM/1174-mobile-active-add-a-note-attach-photo)

**Comment by LinX64** [comment]
[Attach a note | UI/Layout](https://trello.com/c/UIoFqei0/1730-attach-a-note-ui-layout)

**Review by xameYeoh — APPROVED** [review]

**Comment by LinX64** [comment]
@xameYeoh Shall we revert this back? there are still a few items for this feature, I wouldn't rebase them now.

**Comment by xameYeoh** [comment]
> @xameYeoh Shall we revert this back? there are still a few items for this feature, I wouldn't rebase them now.
Sorry about that - wrong order 😝

**Pull request merged**
