### PR TITLE
Navigation | Refactor 2

### PR DESCRIPTION
**Pull request by LinX64**
This PR is related to the navigation with the Mobile Active Tab.

### CODE REVIEW

**Comment by LinX64** [comment]
[mobile dormant & fixed: when returning from map or graph, navigation takes you to the home tab rather than staying on mobile dormant or fixed](https://trello.com/c/U3OuRG9B/1719-mobile-dormant-fixed-when-returning-from-map-or-graph-navigation-takes-you-to-the-home-tab-rather-than-staying-on-mobile-dormant)

**Comment by xameYeoh** [comment]
Is this included in [this pr](https://github.com/HabitatMap/AircastingAndroid/pull/621)? If so, I've rebased it already. I am not sure if the first commit from here will be duplicated or not, maybe we should remove it from here then?

**Comment by LinX64** [comment]
I need to test the Firebase lab, after that I'll close this PR.

**Comment by LinX64** [comment]
[Tests Refactor | New Navigation](https://trello.com/c/OieU6Rtt/1722-tests-refactor-new-navigation)

**Pull request merged**
